### ISSUE TITLE
Not possible to have one Vuex store now?

### ISSUE THREAD

**Issue by Vuete** [marconi1992/hypernova-vue#1]
Hi,

Your library is awesome! But when I try to create multiple components with 1 Vuex store that's not possible anymore?

Or I am doing something wrong?

For example I have 2 renderVuex methods:
`import ProductGrid from './components/Productgrid.vue'`
`import ProductList from './components/Productlist.vue'`
`import createStore from './store'`
`if (name === 'Productgrid') {
    return renderVuex(name, ProductGrid, createStore)
}`
`if (name === 'Productlist') {
    return renderVuex(name, ProductList, createStore)
}`

Then the data in the store is separated.

**Comment by marconi1992** [comment]
Hi @Vuete, sorry for the late response I was busy these last days. That behavior is expected, the objective is to think in a hypernova view as an isolated piece of the UI (kinda Micro-frontends isolation). We should look for other mechanisms to sync the state between multiple views. e.g using the DOM events as pub/sub mechanism.
