### ISSUE TITLE
Error with rendering nested vue components

### ISSUE THREAD

**Issue by bestmazzo** [marconi1992/hypernova-vue#34]
Hi, first of all, thank you for your marvellous work!
I've been trying to convert my project to accomplish a microfrontend approach using Ara Framework, but I'm struggling with this problem:
- starting from the https://github.com/marconi1992/hypernova-vue-example
- included my own component that uses some other vue components in it (specifically: MdIcon from  Vue Material)
- the component itself is rendered, but not the Vue Material subcomponents, and console complaints " Unknown custom element: <md-icon> "

What should I do about that?

**Comment by marconi1992** [comment]
Hi @bestmazzo, I think you need to use the `VueMaterial` middleware.

```
Vue.use(VueMaterial)
```

I created a new branch on the repo `hypernova-vue-example` using Vue Material, you can take a look and run it.

https://github.com/marconi1992/hypernova-vue-example/tree/vue-material

I hope that fixes the issue.

**Comment by bestmazzo** [comment]
Great, thank you I missed the part about Vue.use(vueMaterial).
